dataset:
  description: The dataset to use for training
  type: str
  value: "MNIST"

batchsize:
  description: The batch size to use for the dataloader
  type: int
  value: 128

epochs:
  description: The number of epochs to train the model for
  type: int
  value: 50

gpus:
  description: The number of GPUs to use for training
  type: int
  value: 2

trajectory_length:
  description: The length of the diffusion trajectory
  type: int
  value: 1024
sinusoidal_embedding_size:
  description: The size of the sinusoidal embedding used in the model
  type: int
  value: 128
lr:
  description: The learning rate for training the model
  type: float
  value: 0.0001 # The paper suggests that this is a good learning rate to use for smaller images. For larger images they used 2e-5
ema_decay:
  description: The decay rate for the EMA weight averaging
  type: float
  value: 0.99

