dataset:
  description: The dataset to use for training
  type: str
  value: "CelebA"

batchsize:
  description: The batch size to use for the dataloader
  type: int
  value: 80

epochs:
  description: The number of epochs to train the model for
  type: int
  value: 500

gpus:
  description: The number of GPUs to use for training
  type: int
  value: 2

trajectory_length:
  description: The length of the diffusion trajectory
  type: int
  value: 1000
sinusoidal_embedding_size:
  description: The size of the sinusoidal embedding used in the model
  type: int
  value: 128
lr: # The paper suggests that this is a good learning rate to use for smaller images. For larger images they used 2e-5
  description: The learning rate for training the model
  type: float
  value: 0.0001
ema_decay:
  description: The decay rate for the EMA weight averaging
  type: float
  value: 0.9999 # The paper uses 0.9999, but we don't have 8xV100s handy, so we need to try other values to converge faster

sample_frequency:
  description: The frequency (in epochs) at which to sample from the model and log the samples to wandb
  type: int
  value: 10

metad_basis_size:
  description: The number of past locations to use for the metadynamics loss
  type: int
  value: 16
metad_scale:
  description: The scale of the metadynamics loss
  type: float
  value: 0.01
metad_patience:
  description: The number of epochs to wait before activating metadynamics if the training loss doesn't improve
  type: int
  value: 5
metad_interval:
  description: The number of batches between adding new locations to the metadynamics loss
  type: int
  value: 5