dataset:
  description: The dataset to use for training
  type: str
  value: "Combined"

batchsize:
  description: The batch size to use for the dataloader
  type: int
  value: 48 # Saturates 2 RTX 3090s

epochs:
  description: The number of epochs to train the model for
  type: int
  value: 100

gpus:
  description: The number of GPUs to use for training
  type: int
  value: 2

repa_weight:
  description: The weight to give to the REPA loss
  type: float
  value: 0.5
repa_layer:
  description: The layer of the REPA transformer to apply the REPA loss to (0-indexed)
  type: int
  value: 7
lr:
  description: The learning rate for training the model
  type: float
  value: 0.0001
ema_decay:
  description: The decay rate for the EMA weight averaging
  type: float
  value: 0.9999 # The ddpm paper uses 0.9999

sample_frequency:
  description: The frequency (in epochs) at which to sample from the model and log the samples to wandb
  type: int
  value: 1
