name:
  description: The name of the run, used saving checkpoints and samples locally
  type: str
  value: "pd12m-coco"

dataset:
  description: The dataset to use for training
  type: str
  value: "../pd12m,../coco" # Note, our code automatically parses this as 2 datasets and concatenates them

batchsize:
  description: The batch size to use for the dataloader
  type: int
  value: 64 # Saturates 2 RTX 3090s
accumulate_grad_batches:
  description: The number of batches to accumulate gradients for before performing an optimizer step. Effective batch size = batchsize * accumulate_grad_batches
  type: int
  value: 8

epochs:
  description: The number of epochs to train the model for
  type: int
  value: 10

gpus:
  description: The number of GPUs to use for training
  type: int
  value: 2

repa_weight:
  description: The weight to give to the REPA loss
  type: float
  value: 0.1 # The first stage had a higher REPA weight. We should have aligned representations well enough to not need the REPA loss as much
repa_layer:
  description: The layer of the REPA transformer to apply the REPA loss to (0-indexed)
  type: int
  value: 7

prompt_dropout:
  description: The dropout rate to apply to the prompt embeddings during training. Used for training for classifier free guidance
  type: float
  value: 0.1
cfg_scale:
  description: The scale to apply to the classifier free guidance during sampling. High = more prompt adherence, but may mess with the model if too high
  type: float
  value: 4 # Note, the REPA paper used values from 1.3 all the way to 4 depending on what they were generating

lr:
  description: The learning rate for training the model
  type: float
  value: 0.0001
ema_decay:
  description: The decay rate for the EMA weight averaging
  type: float
  value: 0.9999 # The ddpm paper uses 0.9999

sample_frequency:
  description: The frequency (in epochs) at which to sample from the model and log the samples to wandb
  type: int
  value: 1
